name: CI Implementation
on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: '5.0'
    
            - name: Run Frontend
              run: |
                   cd contact-fox-frontend
                   npm i
                   npm start &
                   sudo apt-get install wait-for-it -y
                   wait-for-it -h localhost -p 3000 -t 10 -q -s -- echo " Frontend is running"

            - name: Run Backend
              run: |
                   cd contact-fox-backend
                   npm i
                   npm start &
                   wait-for-it -h localhost -p 5000 -t 10 -q -s -- echo "Backend is running"

            - name: Run Test  
              run: |
                  cd Features4/tests
                  npm i
                  npm run test:e2e ./e2e/feature/login.feature
